#! /usr/bin/env bash

# Called as: do-it-live name/of/directory/to/watch command-to-run and its args

# Runs a single command, and re-starts it when any file in a watched folder changes.

set -e

watch_me="$1"
shift

while true
do
	coproc "$@"
	coproc monitor {
		inotifywait -r -e create -e move -e modify -e delete -e move_self -e delete_self -e attrib "$watch_me"
		kill $COPROC_PID || true
		wait $COPROC_PID || true
	}
	cat <&"${COPROC[0]}"
	wait $monitor_PID
done
